# Generated by Django 4.2 on 2023-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid_alter_ordermodel_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
