# Generated by Django 4.2 on 2023-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_ordermodel_state_ordermodel_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_revenue', models.IntegerField(null=True)),
            ],
        ),
    ]
